version: '3.8'
services:
    frontend:
        image: antoniopapa1991/frontend
        ports:
            - "8080:80"
        depends_on:
            -   backend

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            -   .:/app
        depends_on:
            -   db

    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: category
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: ZXC123Asd!
        volumes:
            -   ./storage/dbdata:/var/lib/mysql
        ports:
            - "33066:3306"
